version: '3.8'
services:
    grid_endpoint:
        container_name: whitecore-grid
        restart: always
        build: .
        image: flymanos/whitecore-docker-grid:latest
        expose:
            - 8002:8002
        ports:
            - 8002:8002
        links:
            - grid_mysqli
        environment:
            DB_HOST: whitecore_mysqli
            DB_DATABASE: 'whitecore_grid'
            DB_USERNAME: 'whitecore'
            DB_PASSWORD: 'whitecore'

    grid_mysqli:
        container_name: whitecore_mysqli
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'thisisnotasecurepassword'
            MYSQL_USER: 'whitecore'
            MYSQL_PASSWORD: 'whitecore'
            MYSQL_DATABASE: 'whitecore_grid'
        volumes:
            - ./grid-db:/var/lib/mysql
